### ISSUE TITLE
Configuring a custom notifier makes consul-alerts crash on notification

### ISSUE THREAD

**Issue by Rhuagh** [AcalephStorage/consul-alerts#106] opened 2016-03-09 10:42 UTC
customNotifs is only defined, not assigned to a real map (maps in go are reference types).

goroutine 14 [running]:
panic(0x8a23c0, 0xc82020e140)
	/usr/local/go/src/runtime/panic.go:464 +0x3e6
github.com/AcalephStorage/consul-alerts/consul.(*ConsulAlertClient).CustomNotifiers(0xc8201a64f0, 0x0)
	/opt/go/src/github.com/AcalephStorage/consul-alerts/consul/client.go:338 +0x1c2
main.(*NotifEngine).sendCustom(0xc82023fdb0, 0xc820100790, 0x1, 0x1)
	/opt/go/src/github.com/AcalephStorage/consul-alerts/send-notifs.go:65 +0x65
main.(*NotifEngine).start(0xc82023fdb0)
	/opt/go/src/github.com/AcalephStorage/consul-alerts/send-notifs.go:32 +0x12c
created by main.startNotifEngine
	/opt/go/src/github.com/AcalephStorage/consul-alerts/send-notifs.go:102 +0xcc

**Comment by fusiondog** [comment] 2016-04-30 00:04
This is a duplicate of #96 The fix has been merged in.  Closing.

**Closed by fusiondog** 2016-04-30 00:04 UTC
