### ISSUE TITLE
consul-alerts panics: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by awheeler** [AcalephStorage/consul-alerts#62] opened 2015-06-26 18:34 UTC
Consul-alerts always dies with this error after running for about an hour.

Here's the full stack trace: https://gist.github.com/awheeler/dc0f8bd15c1a5e223887

I am running in a docker container, with a consul bin installed locally.  Consul is setup with three consul servers in a cluster.
It's consul 0.5.2, and consul-alerts 0.3.1 (though it returns 0.3.0 with --version).

**Comment by darkcrux** [comment] 2016-01-04 08:48
Hi, Sorry took a while, I couldn't reproduce this. :( 

Are you still having the same issue? There have been changes since then (cleanup/rewrites). Also will release a new build soon with a few more fixes. Might solve this issue.

**Comment by fusiondog** [comment] 2016-08-11 22:26
This regards a very old version of code and no recent update.  Closing pending any change.

**Closed by fusiondog** 2016-08-11 22:26 UTC
