### ISSUE TITLE
How to run --watch-checks from docker container?

### ISSUE THREAD

**Issue by johnjelinek** [AcalephStorage/consul-alerts#55] opened 2015-03-29 22:40 UTC
When using `--watch-checks` / `--watch-events` during a container run, the logs say:

```
$ docker run --name consul-alerts -d acaleph/consul-alerts start --consul-addr=localhost:8500 --consul-dc=dc1 --watch-checks
time="2015-03-29T22:34:59Z" level="info" msg="Shutting down watcher --> Something went wrong running consul watch:  exec: \"consul\": executable file not found in $PATH"
```

**Comment by lyrixx** [comment] 2015-03-29 22:45
You need to install consul first.

**Comment by johnjelinek** [comment] 2015-03-29 22:48
I have consul running in another docker container.



—

**Comment by johnjelinek** [comment] 2015-03-29 22:48
I know consul-alerts connected because all the KVs are in consul



—

**Comment by johnjelinek** [comment] 2015-03-31 04:30
I just tried `--watch-checks` from the `consul-alerts` docker container and `consul watch -type checks consul-alerts watch checks` from the `consul` docker container. Neither work. Is it possible to have them communicate via container linking?

**Comment by vidarh** [comment] 2015-05-06 21:30
The problem is that consul-alerts needs a consul *binary* inside the Docker container as it uses the consul binary as a client to establish the watches. The current Docker container doesn't have that for some reason. Previous versions used to.

You can probably work around that by bind mounting a consul binary via a volume, but it's not exactly ideal.

**Comment by BCWilsonDotCom** [comment] 2015-07-27 19:40
Ran into this as well. I gave docker a flag of '-v /usr/local' so that it would mount the host's /usr/local in the container. This gave the docker container access to the consul binary which lives in /usr/local/bin/

**Comment by BCWilsonDotCom** [comment] 2015-07-30 18:36
@johnjelinek Does this help you out?

**Comment by johnjelinek** [comment] 2015-07-30 18:37
It's a great idea, it probably would help, but I can't test it atm. My consul cluster isn't up anymore.



—

**Comment by dlackty** [comment] 2015-10-05 16:51
@johnjelinek in the latest consul-alerts image, there's a built in consul installation. Could you give it a try?

**Comment by BCWilsonDotCom** [comment] 2015-10-10 01:53
With the addition of the consul binary in the docker container, I think we can probably close this issue.

**Comment by darkcrux** [comment] 2016-01-04 09:07
Thanks guys. Closing this issue now.

**Comment by fusiondog** [comment] 2016-05-05 22:51
Added some more notes on launching via docker with the new smaller alpine based docker image.

**Closed by fusiondog** 2016-05-05 22:51 UTC
